openapi: 3.0.0
info:
  title: Simple Search API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local Developerment Server
paths:
  /search:
    get:
      summary: Search (fulltext, timerange and term filter) with limit an offset
      parameters:
        - in: query
          name: q
          description: a search string for fulltext search
          schema:
            type: string
        - in: query
          name: tag
          description: one or more tags for result filtering
          schema:
            type: array
            items:
              type: string
        - in: query
          name: range
          schema:
            type: string
            enum:
              - PAST_HOUR
              - PAST_DAY
              - PAST_WEEK
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: the search result
          content:
            application/json:
              schema:
                type: object
                properties:
                  limit:
                    type: integer
                  offest:
                    type: integer
                  numOfResults:
                    type: integer
                  docs:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        date:
                          type: string
                        tags:
                          type: array
                          items:
                            type: string
                        rating:
                          type: number
                          format: double
                        scoring:
                          type: number
                          format: double
                  tags:
                    description: the tag facets
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                        count:
                          type: integer
